[package]
name = "hypernote-mdx"
version = "0.3.0"
edition = "2024"

[dependencies]
serde_json = "1"

[lib]
name = "hypernote_mdx"
path = "src/lib.rs"

[[bin]]
name = "mdx-parse"
path = "src/main.rs"

[[bin]]
name = "mdx-view"
path = "src/mdx_view.rs"
